download: Fix jinja2 template associated with download_stats_url
This commit removes the extra space causing the following error when
using the generated download templates:

  File "/home/jcfr/Projects/slicer_download/slicer_download_server/templates/download.html", line 283, in template
    <a href="{{%20download_stats_url%20}}" class="navbar-item">
  jinja2.exceptions.TemplateSyntaxError: unexpected '%'